### ISSUE TITLE
Viewing error on macOS 12

### ISSUE THREAD

**Issue by bhchiang** [homebrew-zathura/homebrew-zathura#81]
I installed zathura with the following commands on macOS 12 (Beta):

![image](https://user-images.githubusercontent.com/70753792/135381529-ed65f8f4-b972-4118-be4b-7a3400dc8294.png)

But when I open any PDF, I run into the following error.

![image](https://user-images.githubusercontent.com/70753792/135380390-1b24c3ed-724a-4918-a527-d48da7375e9e.png)

Any suggestions appreciated, thanks!

**Comment by zegervdv** [comment]
This seems like an HiDPI scaling issue, as the titlebar is rendered correctly.
I don't have macOS 12 yet, so I have no way to reproduce it.

Have you tried with the `zathura-pdf-poppler` plugin to see if it is a general issue or only with mupdf?
You will need to remove the mupdf plugin first from the plugin dir: `$(brew --prefix zathura)/lib/zathura/libpdf-mupdf.dylib`.

Other things you could try:
 * install with `--HEAD` to include the latest development changes, maybe some issue is already fixed upstream
 * try exporting the `GDK_SCALE` variable to a value of 1 or 2

**Comment by zegervdv** [comment]
@bryanhpchiang there may be a fix for this: you could try using a patched gtk3 library:
```
brew uninstall --ignore-dependencies gtk+3
brew install ttarhan/gtk-fix/gtk+3
```

See #83 for more info

**Comment by cobcobs** [comment]
Hello, I am running into a similar problem, albeit with smaller gaps:

![image](https://user-images.githubusercontent.com/44166162/216757304-c98f990c-bcfe-4f5a-b987-335e70961f47.png)

This issue persists across macOS 12 and 13, and also persists whether I use `zathura-pdf-poppler` or `mupdf`. Exporting `GDK_SCALE` to 1 or 2 does not solve the issue either.

Any help is appreciated, thank you.

@zegervdv
